server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
#   数据库索引
    database: 0
    password:

logging:
  config: classpath:config/logback.xml
  level:
    root: debug
jdbc:
  url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  username: root
  password: root
  initialSize: 1
  maxActive: 200
  minIdle: 2
  maxWait: 30000
  minEvictableIdleTimeMillis: 300000
  timeBetweenEvictionRunsMillis: 60000
